// front_react/src/components/backoffice/VenueForm.tsx
import { useEffect, useState } from 'react'
import { Box, Button, Grid, TextField, Typography } from '@mui/material'
import type { Venue, VenueData } from '@portfolio/shared'

interface Props {
  initial?: Venue
  loading?: boolean
  onSubmit: (data: Omit<VenueData, 'id'>) => void
  onCancel: () => void
}

export default function VenueForm({ initial, loading, onSubmit, onCancel }: Props) {
  const [name, setName] = useState('')
  const [city, setCity] = useState('')
  const [address1, setAddress1] = useState('')
  const [zipCode, setZipCode] = useState('')
  const [errors, setErrors] = useState({ name: '', city: '' })

  useEffect(() => {
    if (initial) {
      setName(initial.name)
      setCity(initial.city)
      setAddress1(initial.address1 ?? '')
      setZipCode(initial.zipCode ?? '')
    }
  }, [initial])

  function validate(): boolean {
    const e = { name: '', city: '' }
    if (!name) e.name = 'Champ requis'
    if (!city) e.city = 'Champ requis'
    setErrors(e)
    return !e.name && !e.city
  }

  function submit(evt: React.FormEvent) {
    evt.preventDefault()
    if (!validate()) return
    onSubmit({ name, city, address1: address1 || undefined, zipCode: zipCode || undefined })
    if (!initial) {
      setName(''); setCity(''); setAddress1(''); setZipCode('')
    }
  }

  return (
    <Box component="form" onSubmit={submit}>
      <Typography variant="h6" sx={{ mb: 3 }} data-testid="venue-dialog-title">{initial ? 'Modifier le lieu' : 'Nouveau lieu'}</Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={6}>
          <TextField label="Nom du lieu *" fullWidth variant="outlined" size="small"
            value={name} onChange={(e) => setName(e.target.value)}
            error={!!errors.name} helperText={errors.name}
            inputProps={{ 'data-testid': 'venue-name-input' }} />
        </Grid>
        <Grid item xs={12} sm={6}>
          <TextField label="Ville *" fullWidth variant="outlined" size="small"
            value={city} onChange={(e) => setCity(e.target.value)}
            error={!!errors.city} helperText={errors.city}
            inputProps={{ 'data-testid': 'venue-city-input' }} />
        </Grid>
        <Grid item xs={12} sm={8}>
          <TextField label="Adresse" fullWidth variant="outlined" size="small"
            value={address1} onChange={(e) => setAddress1(e.target.value)} />
        </Grid>
        <Grid item xs={12} sm={4}>
          <TextField label="Code postal" fullWidth variant="outlined" size="small"
            value={zipCode} onChange={(e) => setZipCode(e.target.value)} />
        </Grid>
      </Grid>
      <Box sx={{ display: 'flex', gap: 1, mt: 3 }}>
        <Button type="submit" variant="contained" disabled={loading} data-testid="save-btn">Enregistrer</Button>
        <Button variant="text" onClick={onCancel}>Annuler</Button>
      </Box>
    </Box>
  )
}

// front_vue/src/components/backoffice/VenueForm.vue
<template>
  <v-form @submit.prevent="submit" ref="formRef">
    <p class="text-h6 mb-4" data-testid="venue-dialog-title">{{ initial ? 'Modifier le lieu' : 'Nouveau lieu' }}</p>
    <v-row>
      <v-col cols="12" sm="6">
        <v-text-field
          v-model="form.name"
          label="Nom du lieu *"
          variant="outlined"
          density="comfortable"
          :rules="[required]"
          data-testid="venue-name-input"
        />
      </v-col>
      <v-col cols="12" sm="6">
        <v-text-field
          v-model="form.city"
          label="Ville *"
          variant="outlined"
          density="comfortable"
          :rules="[required]"
          data-testid="venue-city-input"
        />
      </v-col>
      <v-col cols="12" sm="8">
        <v-text-field
          v-model="form.address1"
          label="Adresse"
          variant="outlined"
          density="comfortable"
        />
      </v-col>
      <v-col cols="12" sm="4">
        <v-text-field
          v-model="form.zipCode"
          label="Code postal"
          variant="outlined"
          density="comfortable"
        />
      </v-col>
    </v-row>
    <div class="d-flex gap-2 mt-2">
      <v-btn type="submit" color="primary" :loading="loading" data-testid="save-btn">Enregistrer</v-btn>
      <v-btn variant="text" @click="$emit('cancel')">Annuler</v-btn>
    </div>
  </v-form>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import type { Venue, VenueData } from '@portfolio/shared'

const props = defineProps<{ loading?: boolean; initial?: Venue }>()

const emit = defineEmits<{
  submit: [data: Omit<VenueData, 'id'>]
  cancel: []
}>()

const formRef = ref()
const form = reactive({ name: '', city: '', address1: '', zipCode: '' })

onMounted(() => {
  if (props.initial) {
    Object.assign(form, {
      name: props.initial.name,
      city: props.initial.city,
      address1: props.initial.address1 ?? '',
      zipCode: props.initial.zipCode ?? '',
    })
  }
})

const required = (v: string) => !!v || 'Champ requis'

async function submit() {
  const { valid } = await formRef.value.validate()
  if (!valid) return
  emit('submit', { ...form })
  if (!props.initial) {
    Object.assign(form, { name: '', city: '', address1: '', zipCode: '' })
  }
}
</script>
