// front_angular/src/app/layout/admin/admin-layout.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, Router } from '@angular/router';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatListModule } from '@angular/material/list';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { AuthStore } from '../../core/stores/auth.store';

interface NavItem {
  label: string;
  icon: string;
  path: string;
}

const NAV_ITEMS: NavItem[] = [
  { label: 'Lieux', icon: 'place', path: '/backoffice/venues' },
  { label: 'Concerts', icon: 'music_note', path: '/backoffice/shows' },
  { label: 'Sécurité MFA', icon: 'shield', path: '/backoffice/mfa-setup' },
];

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [
    RouterLink,
    RouterLinkActive,
    MatToolbarModule,
    MatSidenavModule,
    MatListModule,
    MatButtonModule,
    MatIconModule,
  ],
  template: `
    <mat-sidenav-container class="admin-container">
      <mat-sidenav mode="side" opened class="admin-drawer">
        <div class="drawer-toolbar-spacer"></div>
        <mat-nav-list>
          @for (item of navItems; track item.path) {
            <a mat-list-item
               [routerLink]="item.path"
               routerLinkActive="active-nav"
               class="nav-item">
              <mat-icon matListItemIcon>{{ item.icon }}</mat-icon>
              <span matListItemTitle>{{ item.label }}</span>
            </a>
          }
          @if (auth.isAdmin()) {
            <a mat-list-item
               routerLink="/backoffice/users"
               routerLinkActive="active-nav"
               class="nav-item">
              <mat-icon matListItemIcon>people</mat-icon>
              <span matListItemTitle>Utilisateurs</span>
            </a>
            <a mat-list-item
               routerLink="/backoffice/messages"
               routerLinkActive="active-nav"
               class="nav-item">
              <mat-icon matListItemIcon>mail</mat-icon>
              <span matListItemTitle>Messages</span>
            </a>
          }
        </mat-nav-list>
      </mat-sidenav>

      <mat-sidenav-content>
        <mat-toolbar color="primary" class="admin-toolbar">
          <span class="toolbar-title">Portfolio — Backoffice</span>
          <button mat-button (click)="logout()" data-testid="logout-btn">Déconnexion</button>
        </mat-toolbar>

        <main class="admin-main">
          <ng-content />
        </main>
      </mat-sidenav-content>
    </mat-sidenav-container>
  `,
  styles: [`
    .admin-container {
      height: 100vh;
    }

    .admin-drawer {
      width: 240px;
      padding-top: 64px;
    }

    .drawer-toolbar-spacer {
      height: 0;
    }

    .admin-toolbar {
      position: sticky;
      top: 0;
      z-index: 1000;

      .toolbar-title {
        flex: 1;
      }
    }

    .admin-main {
      padding: 1.5rem;
    }

    .nav-item {
      &.active-nav {
        background-color: rgba(98, 0, 238, 0.12);
        color: #6200EE;

        mat-icon {
          color: #6200EE;
        }
      }
    }
  `],
})
export class AdminLayoutComponent {
  protected readonly auth = inject(AuthStore);
  protected readonly navItems = NAV_ITEMS;

  private readonly router = inject(Router);

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }
}

// front_react/src/components/layout/AdminLayout.tsx
import {
  AppBar, Box, Drawer, List, ListItem, ListItemButton,
  ListItemIcon, ListItemText, Toolbar, Typography, Button,
} from '@mui/material'
import PlaceIcon from '@mui/icons-material/Place'
import MusicNoteIcon from '@mui/icons-material/MusicNote'
import ShieldIcon from '@mui/icons-material/Shield'
import PeopleIcon from '@mui/icons-material/People'
import MailIcon from '@mui/icons-material/Mail'
import { NavLink, useNavigate } from 'react-router-dom'
import type { ReactNode } from 'react'
import { useAuthStore } from '@/stores/authStore'

const DRAWER_WIDTH = 240

interface Props {
  children: ReactNode
}

const navItems = [
  { label: 'Lieux', icon: <PlaceIcon />, to: '/backoffice/venues' },
  { label: 'Concerts', icon: <MusicNoteIcon />, to: '/backoffice/shows' },
  { label: 'Sécurité MFA', icon: <ShieldIcon />, to: '/backoffice/mfa-setup' },
]

export default function AdminLayout({ children }: Props) {
  const { logout, isAdmin } = useAuthStore()
  const navigate = useNavigate()

  function handleLogout() {
    logout()
    navigate('/login')
  }

  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar position="fixed" sx={{ zIndex: (t) => t.zIndex.drawer + 1 }}>
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            Portfolio — Backoffice
          </Typography>
          <Button color="inherit" onClick={handleLogout} data-testid="logout-btn">Déconnexion</Button>
        </Toolbar>
      </AppBar>

      <Drawer
        variant="permanent"
        sx={{
          width: DRAWER_WIDTH,
          flexShrink: 0,
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
      >
        <Toolbar />
        <List>
          {navItems.map((item) => (
            <ListItem key={item.to} disablePadding>
              <ListItemButton
                component={NavLink}
                to={item.to}
                sx={{
                  '&.active': { backgroundColor: 'rgba(98, 0, 238, 0.12)', color: 'primary.main' },
                  '&.active .MuiListItemIcon-root': { color: 'primary.main' },
                }}
              >
                <ListItemIcon>{item.icon}</ListItemIcon>
                <ListItemText primary={item.label} />
              </ListItemButton>
            </ListItem>
          ))}
          {isAdmin && (
            <>
              <ListItem disablePadding>
                <ListItemButton
                  component={NavLink}
                  to="/backoffice/users"
                  sx={{
                    '&.active': { backgroundColor: 'rgba(98, 0, 238, 0.12)', color: 'primary.main' },
                    '&.active .MuiListItemIcon-root': { color: 'primary.main' },
                  }}
                >
                  <ListItemIcon><PeopleIcon /></ListItemIcon>
                  <ListItemText primary="Utilisateurs" />
                </ListItemButton>
              </ListItem>
              <ListItem disablePadding>
                <ListItemButton
                  component={NavLink}
                  to="/backoffice/messages"
                  sx={{
                    '&.active': { backgroundColor: 'rgba(98, 0, 238, 0.12)', color: 'primary.main' },
                    '&.active .MuiListItemIcon-root': { color: 'primary.main' },
                  }}
                >
                  <ListItemIcon><MailIcon /></ListItemIcon>
                  <ListItemText primary="Messages" />
                </ListItemButton>
              </ListItem>
            </>
          )}
        </List>
      </Drawer>

      <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
        <Toolbar />
        {children}
      </Box>

    </Box>
  )
}
