// front_react/src/components/layout/AdminLayout.tsx
import {
  AppBar, Box, Drawer, List, ListItem, ListItemButton,
  ListItemIcon, ListItemText, Toolbar, Typography, Button,
} from '@mui/material'
import PlaceIcon from '@mui/icons-material/Place'
import MusicNoteIcon from '@mui/icons-material/MusicNote'
import ShieldIcon from '@mui/icons-material/Shield'
import PeopleIcon from '@mui/icons-material/People'
import { NavLink, useNavigate } from 'react-router-dom'
import type { ReactNode } from 'react'
import { useAuthStore } from '@/stores/authStore'

const DRAWER_WIDTH = 240

interface Props {
  children: ReactNode
}

const navItems = [
  { label: 'Lieux', icon: <PlaceIcon />, to: '/backoffice/venues' },
  { label: 'Concerts', icon: <MusicNoteIcon />, to: '/backoffice/shows' },
  { label: 'Sécurité MFA', icon: <ShieldIcon />, to: '/backoffice/mfa-setup' },
]

export default function AdminLayout({ children }: Props) {
  const { logout, isAdmin } = useAuthStore()
  const navigate = useNavigate()

  function handleLogout() {
    logout()
    navigate('/login')
  }

  return (
    <Box sx={{ display: 'flex' }}>
      <AppBar position="fixed" sx={{ zIndex: (t) => t.zIndex.drawer + 1 }}>
        <Toolbar>
          <Typography variant="h6" sx={{ flexGrow: 1 }}>
            Portfolio — Backoffice
          </Typography>
          <Button color="inherit" onClick={handleLogout} data-testid="logout-btn">Déconnexion</Button>
        </Toolbar>
      </AppBar>

      <Drawer
        variant="permanent"
        sx={{
          width: DRAWER_WIDTH,
          flexShrink: 0,
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
      >
        <Toolbar />
        <List>
          {navItems.map((item) => (
            <ListItem key={item.to} disablePadding>
              <ListItemButton
                component={NavLink}
                to={item.to}
                sx={{
                  '&.active': { backgroundColor: 'rgba(98, 0, 238, 0.12)', color: 'primary.main' },
                  '&.active .MuiListItemIcon-root': { color: 'primary.main' },
                }}
              >
                <ListItemIcon>{item.icon}</ListItemIcon>
                <ListItemText primary={item.label} />
              </ListItemButton>
            </ListItem>
          ))}
          {isAdmin && (
            <ListItem disablePadding>
              <ListItemButton
                component={NavLink}
                to="/backoffice/users"
                sx={{
                  '&.active': { backgroundColor: 'rgba(98, 0, 238, 0.12)', color: 'primary.main' },
                  '&.active .MuiListItemIcon-root': { color: 'primary.main' },
                }}
              >
                <ListItemIcon><PeopleIcon /></ListItemIcon>
                <ListItemText primary="Utilisateurs" />
              </ListItemButton>
            </ListItem>
          )}
        </List>
      </Drawer>

      <Box component="main" sx={{ flexGrow: 1, p: 3 }}>
        <Toolbar />
        {children}
      </Box>

    </Box>
  )
}

// front_vue/src/components/layout/AdminLayout.vue
<template>
  <v-app theme="light">
    <v-app-bar color="primary" flat>
      <v-app-bar-title>Portfolio — Backoffice</v-app-bar-title>
      <template #append>
        <v-btn variant="text" data-testid="logout-btn" @click="handleLogout">Déconnexion</v-btn>
      </template>
    </v-app-bar>
    <v-navigation-drawer permanent>
      <v-list nav>
        <v-list-item
          title="Lieux"
          prepend-icon="mdi-map-marker"
          to="/backoffice/venues"
        />
        <v-list-item
          title="Concerts"
          prepend-icon="mdi-music"
          to="/backoffice/shows"
        />
        <v-list-item
          title="Sécurité MFA"
          prepend-icon="mdi-shield-key"
          to="/backoffice/mfa-setup"
        />
        <v-list-item
          v-if="auth.isAdmin"
          title="Utilisateurs"
          prepend-icon="mdi-account-multiple"
          to="/backoffice/users"
        />
      </v-list>
    </v-navigation-drawer>
    <v-main>
      <v-container fluid>
        <slot />
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/authStore'

const auth = useAuthStore()
const router = useRouter()

function handleLogout() {
  auth.logout()
  router.push('/login')
}
</script>
