// front_react/src/components/layout/PublicLayout.tsx
import { Box, Container } from '@mui/material'
import { Link, NavLink } from 'react-router-dom'
import type { ReactNode } from 'react'
import logo from '@/assets/logo.png'
import bgImg from '@/assets/bg.jpg'

interface Props {
  children: ReactNode
}

export default function PublicLayout({ children }: Props) {
  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', backgroundColor: '#1a1a1a', color: '#fff' }}>
      <Box
        component="header"
        sx={{
          height: 300,
          backgroundImage: `url(${bgImg})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 2,
        }}
      >
        <Link to="/">
          <Box component="img" src={logo} alt="Portfolio" sx={{ maxWidth: 400, maxHeight: 200, objectFit: 'contain' }} />
        </Link>
        <Box component="nav" sx={{ display: 'flex', gap: 4 }}>
          <NavLink to="/" end style={navStyle}>Accueil</NavLink>
          <NavLink to="/shows" style={navStyle}>Concerts</NavLink>
          <NavLink to="/contact" style={navStyle}>Contact</NavLink>
        </Box>
      </Box>

      <Container component="main" maxWidth="lg" sx={{ flex: 1, py: 4 }}>
        {children}
      </Container>

      <Box component="footer" sx={{ py: 2, textAlign: 'center', color: '#888', fontSize: '0.9rem' }}>
        <p>&copy; {new Date().getFullYear()} Portfolio</p>
      </Box>

    </Box>
  )
}

function navStyle({ isActive }: { isActive: boolean }): React.CSSProperties {
  return {
    color: '#ffffff',
    textDecoration: 'none',
    fontSize: '1.1rem',
    borderBottom: isActive ? '2px solid #000' : 'none',
  }
}

// front_vue/src/components/layout/PublicLayout.vue
<template>
  <div class="public-layout">
    <header class="public-header">
      <router-link to="/">
        <img src="@/assets/logo.png" alt="Portfolio" class="logo" />
      </router-link>
      <nav>
        <router-link to="/">Accueil</router-link>
        <router-link to="/shows">Concerts</router-link>
        <router-link to="/contact">Contact</router-link>
      </nav>
    </header>
    <main class="public-content">
      <slot />
    </main>
    <footer class="public-footer">
      <p>&copy; {{ new Date().getFullYear() }} Portfolio</p>
    </footer>
  </div>
</template>

<style scoped>
.public-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: #1a1a1a;
  color: #ffffff;
}

.public-header {
  height: 300px;
  background-image: url("@/assets/bg.jpg");
  background-size: cover;
  background-position: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1rem;
}

.logo {
  max-width: 400px;
  max-height: 200px;
  object-fit: contain;
}

nav {
  display: flex;
  gap: 2rem;
}

nav a {
  color: #ffffff;
  text-decoration: none;
  font-size: 1.1rem;
}

nav a.router-link-active {
  border-bottom: 2px solid var(--color-accent-menu);
}

.public-content {
  flex: 1;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

.public-footer {
  padding: 1rem 2rem;
  text-align: center;
  color: #888;
  font-size: 0.9rem;
}
</style>
