// front_react/src/pages/Shows.tsx
import { useEffect, useMemo } from 'react'
import { Alert, Box, LinearProgress, Typography } from '@mui/material'
import PublicLayout from '@/components/layout/PublicLayout'
import { useShowStore } from '@/stores/showStore'
import type { Show } from '@portfolio/shared'

function formatDate(show: Show): string {
  const d = show.date
  return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`
}

function formatRest(show: Show): string {
  const zip = show.venue?.zipCode ? ` (${show.venue.zipCode})` : ''
  const venue = show.venue ? `${show.venue.name} — ${show.venue.city}${zip}` : '—'
  const details = show.details ? `  ${show.details}` : ''
  return `${venue}${details}`
}

export default function Shows() {
  const { shows, loading, error, load } = useShowStore()

  useEffect(() => { load() }, [load])

  const upcoming = useMemo(() =>
    shows
      .filter((s) => s.date >= new Date())
      .sort((a, b) => a.date.getTime() - b.date.getTime()),
    [shows],
  )

  const past = useMemo(() =>
    shows
      .filter((s) => s.date < new Date())
      .sort((a, b) => b.date.getTime() - a.date.getTime()),
    [shows],
  )

  return (
    <PublicLayout>
      <Typography variant="h4" sx={{ fontWeight: 300, letterSpacing: '0.15em', textTransform: 'uppercase', color: '#c59a47', mb: 4 }} data-testid="shows-heading">
        Concerts
      </Typography>

      {loading && <LinearProgress color="primary" sx={{ mb: 4 }} />}
      {error && <Alert severity="error" sx={{ mb: 4 }}>{error}</Alert>}

      {!loading && (
        <>
          {upcoming.length > 0 && (
            <Box component="ul" sx={{ listStyle: 'none', p: 0, m: 0, mb: 6 }}>
              {upcoming.map((show) => (
                <ShowItem key={show.id} show={show} />
              ))}
            </Box>
          )}

          {past.length > 0 && (
            <>
              <Typography sx={{ fontSize: '1rem', fontWeight: 500, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#aaa', mb: 2 }}>
                Passés
              </Typography>
              <Box component="ul" sx={{ listStyle: 'none', p: 0, m: 0, opacity: 0.5 }}>
                {past.map((show) => (
                  <ShowItem key={show.id} show={show} />
                ))}
              </Box>
            </>
          )}

          {!upcoming.length && !past.length && (
            <Typography sx={{ color: '#666', textAlign: 'center', mt: 8 }}>
              Aucun concert pour le moment.
            </Typography>
          )}
        </>
      )}
    </PublicLayout>
  )
}

function ShowItem({ show }: { show: Show }) {
  return (
    <Box
      component="li"
      sx={{
        py: 0.75,
        borderBottom: '1px solid rgba(255,255,255,0.06)',
        '&:last-child': { borderBottom: 'none' },
        display: 'flex',
        flexDirection: 'column',
        gap: '0.15rem',
      }}
    >
      <Typography sx={{ fontSize: '1rem', color: '#e0e0e0', fontVariantNumeric: 'tabular-nums' }}>
        <Box component="span" sx={{ color: '#c59a47' }}>{formatDate(show)}</Box>
        {'  '}{formatRest(show)}
      </Typography>
      {show.label && (
        <Typography sx={{ fontSize: '0.85rem', color: '#888', fontStyle: 'italic' }}>
          {show.label}
        </Typography>
      )}
    </Box>
  )
}

// front_angular/src/app/pages/shows/shows.component.ts
import { Component, inject, OnInit, computed } from '@angular/core';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { PublicLayoutComponent } from '../../layout/public/public-layout.component';
import { ShowStore } from '../../core/stores/show.store';
import type { Show } from '@portfolio/shared';

function formatDate(show: Show): string {
  const d = show.date;
  return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`;
}

function formatRest(show: Show): string {
  const zip = show.venue?.zipCode ? ` (${show.venue.zipCode})` : '';
  const venue = show.venue ? `${show.venue.name} — ${show.venue.city}${zip}` : '—';
  return show.details ? `${venue}  ${show.details}` : venue;
}

@Component({
  selector: 'app-shows',
  standalone: true,
  imports: [MatProgressBarModule, PublicLayoutComponent],
  template: `
    <app-public-layout>
      <h1 class="page-title" data-testid="shows-heading">Concerts</h1>

      @if (store.loading()) {
        <mat-progress-bar mode="indeterminate" color="primary" />
      }

      @if (store.error()) {
        <div class="error-msg">{{ store.error() }}</div>
      }

      @if (!store.loading()) {
        @if (upcoming().length > 0) {
          <ul class="show-list">
            @for (show of upcoming(); track show.id) {
              <li class="show-item">
                <span class="show-date">{{ fmtDate(show) }}</span>
                <span class="show-rest">  {{ fmtRest(show) }}</span>
                @if (show.label) {
                  <span class="show-label">{{ show.label }}</span>
                }
              </li>
            }
          </ul>
        }

        @if (past().length > 0) {
          <p class="past-label">Passés</p>
          <ul class="show-list past">
            @for (show of past(); track show.id) {
              <li class="show-item">
                <span class="show-date">{{ fmtDate(show) }}</span>
                <span class="show-rest">  {{ fmtRest(show) }}</span>
                @if (show.label) {
                  <span class="show-label">{{ show.label }}</span>
                }
              </li>
            }
          </ul>
        }

        @if (upcoming().length === 0 && past().length === 0) {
          <p class="empty-msg">Aucun concert pour le moment.</p>
        }
      }
    </app-public-layout>
  `,
  styles: [`
    .page-title {
      font-weight: 300;
      letter-spacing: 0.15em;
      text-transform: uppercase;
      color: #c59a47;
      font-size: 2rem;
      margin: 0 0 2rem;
    }

    .show-list {
      list-style: none;
      padding: 0;
      margin: 0 0 2rem;
    }

    .past { opacity: 0.5; }

    .show-item {
      padding: 0.5rem 0;
      border-bottom: 1px solid rgba(255, 255, 255, 0.06);
      display: flex;
      flex-direction: column;
      gap: 0.1rem;

      &:last-child { border-bottom: none; }
    }

    .show-date {
      color: #c59a47;
      font-variant-numeric: tabular-nums;
    }

    .show-rest { color: #e0e0e0; }

    .show-label {
      font-size: 0.85rem;
      color: #888;
      font-style: italic;
    }

    .past-label {
      font-size: 1rem;
      font-weight: 500;
      text-transform: uppercase;
      letter-spacing: 0.1em;
      color: #aaa;
      margin: 0 0 0.5rem;
    }

    .empty-msg {
      color: #666;
      text-align: center;
      margin-top: 4rem;
    }

    .error-msg {
      color: #cf6679;
      border: 1px solid #cf6679;
      border-radius: 4px;
      padding: 0.75rem 1rem;
      margin-bottom: 1rem;
    }
  `],
})
export class ShowsComponent implements OnInit {
  protected readonly store = inject(ShowStore);

  protected readonly upcoming = computed(() => {
    const now = new Date();
    return this.store.shows()
      .filter((s) => s.date >= now)
      .sort((a, b) => a.date.getTime() - b.date.getTime());
  });

  protected readonly past = computed(() => {
    const now = new Date();
    return this.store.shows()
      .filter((s) => s.date < now)
      .sort((a, b) => b.date.getTime() - a.date.getTime());
  });

  protected readonly fmtDate = formatDate;
  protected readonly fmtRest = formatRest;

  ngOnInit(): void {
    this.store.load();
  }
}
