// front_react/src/pages/backoffice/Shows.tsx
import { useEffect, useState } from 'react'
import {
  Alert, Box, Button, Dialog, DialogContent, DialogContentText,
  DialogTitle, DialogActions, IconButton, Typography,
} from '@mui/material'
import { DataGrid } from '@mui/x-data-grid'
import type { GridColDef } from '@mui/x-data-grid'
import AddIcon from '@mui/icons-material/Add'
import EditIcon from '@mui/icons-material/Edit'
import DeleteIcon from '@mui/icons-material/Delete'
import AdminLayout from '@/components/layout/AdminLayout'
import ShowForm from '@/components/backoffice/ShowForm'
import { useShowStore } from '@/stores/showStore'
import { useVenueStore } from '@/stores/venueStore'
import type { ShowData, ShowWithCreator } from '@portfolio/shared'

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' })
}

export default function BackofficeShows() {
  const showStore = useShowStore()
  const venueStore = useVenueStore()
  const [createOpen, setCreateOpen] = useState(false)
  const [editTarget, setEditTarget] = useState<ShowWithCreator | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<ShowWithCreator | null>(null)

  useEffect(() => {
    showStore.loadBackoffice()
    venueStore.load()
  }, [])

  async function handleCreate(data: Omit<ShowData, 'id' | 'venue'>) {
    await showStore.create(data)
    if (!showStore.error) { setCreateOpen(false); showStore.loadBackoffice() }
  }

  async function handleEdit(data: Omit<ShowData, 'id' | 'venue'>) {
    if (!editTarget) return
    await showStore.update(editTarget.id, data)
    if (!showStore.error) { setEditTarget(null); showStore.loadBackoffice() }
  }

  async function handleDelete() {
    if (!deleteTarget) return
    await showStore.remove(deleteTarget.id)
    if (!showStore.error) { setDeleteTarget(null); showStore.loadBackoffice() }
  }

  const columns: GridColDef<ShowWithCreator>[] = [
    {
      field: 'date', headerName: 'Date', flex: 1, sortable: true,
      valueFormatter: (v) => formatDate(v as string),
    },
    { field: 'label', headerName: 'Concert', flex: 1, sortable: true, valueFormatter: (v) => v || '—' },
    {
      field: 'venue', headerName: 'Lieu', flex: 1.5, sortable: false,
      valueGetter: (_v, row) => row.venue ? `${row.venue.name} — ${row.venue.city}` : '—',
    },
    {
      field: 'createdBy', headerName: 'Créé par', flex: 1, sortable: false,
      valueGetter: (_v, row) => row.createdBy?.email || '—',
    },
    {
      field: 'createdAt', headerName: 'Créé le', flex: 1, sortable: true,
      valueFormatter: (v) => formatDate(v as string),
    },
    {
      field: 'actions', headerName: '', width: 90, sortable: false,
      renderCell: ({ row }) => (
        <>
          <IconButton size="small" onClick={() => setEditTarget(row)}><EditIcon fontSize="small" /></IconButton>
          <IconButton size="small" color="error" onClick={() => setDeleteTarget(row)}><DeleteIcon fontSize="small" /></IconButton>
        </>
      ),
    },
  ]

  return (
    <AdminLayout>
      <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 3 }}>
        <Typography variant="h5">Concerts</Typography>
        <Button variant="contained" startIcon={<AddIcon />} onClick={() => setCreateOpen(true)} data-testid="add-show-btn">
          Ajouter un concert
        </Button>
      </Box>

      {showStore.error && <Alert severity="error" sx={{ mb: 2 }}>{showStore.error}</Alert>}

      <DataGrid
        rows={showStore.backofficeShows}
        columns={columns}
        loading={showStore.loading}
        autoHeight
        disableRowSelectionOnClick
        initialState={{ sorting: { sortModel: [{ field: 'date', sort: 'desc' }] } }}
        sx={{ backgroundColor: 'background.paper' }}
      />

      <Dialog open={createOpen} onClose={() => setCreateOpen(false)} maxWidth="sm" fullWidth>
        <DialogContent>
          <ShowForm venues={venueStore.venues} loading={showStore.loading} onSubmit={handleCreate} onCancel={() => setCreateOpen(false)} />
        </DialogContent>
      </Dialog>

      <Dialog open={!!editTarget} onClose={() => setEditTarget(null)} maxWidth="sm" fullWidth>
        <DialogContent>
          {editTarget && (
            <ShowForm
              initial={editTarget}
              venues={venueStore.venues}
              loading={showStore.loading}
              onSubmit={handleEdit}
              onCancel={() => setEditTarget(null)}
            />
          )}
        </DialogContent>
      </Dialog>

      <Dialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} maxWidth="xs" fullWidth>
        <DialogTitle>Confirmer la suppression</DialogTitle>
        <DialogContentText sx={{ px: 3 }}>
          Supprimer le concert <strong>{deleteTarget?.label || 'sans titre'}</strong> ?<br />
          Cette action est irréversible.
        </DialogContentText>
        <DialogActions>
          <Button onClick={() => setDeleteTarget(null)}>Annuler</Button>
          <Button color="error" onClick={handleDelete} disabled={showStore.loading}>Supprimer</Button>
        </DialogActions>
      </Dialog>
    </AdminLayout>
  )
}

// front_angular/src/app/pages/backoffice/shows/shows.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatDialogModule, MatDialog } from '@angular/material/dialog';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { AdminLayoutComponent } from '../../../layout/admin/admin-layout.component';
import { ShowStore } from '../../../core/stores/show.store';
import { VenueStore } from '../../../core/stores/venue.store';
import { ShowFormDialogComponent } from './show-form-dialog.component';
import { Show } from '@portfolio/shared';
import type { ShowData, ShowWithCreator } from '@portfolio/shared';

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric' });
}

@Component({
  selector: 'app-backoffice-shows',
  standalone: true,
  imports: [
    MatTableModule,
    MatButtonModule,
    MatIconModule,
    MatDialogModule,
    MatProgressBarModule,
    AdminLayoutComponent,
  ],
  template: `
    <app-admin-layout>
      <div class="page-header">
        <h1 class="page-title">Concerts</h1>
        <button mat-raised-button color="primary" (click)="openCreate()" data-testid="add-show-btn">
          <mat-icon>add</mat-icon> Ajouter un concert
        </button>
      </div>

      @if (showStore.error()) {
        <div class="error-msg">{{ showStore.error() }}</div>
      }

      @if (showStore.loading()) {
        <mat-progress-bar mode="indeterminate" color="primary" />
      }

      <div class="table-wrapper">
        <table mat-table [dataSource]="showStore.backofficeShows()" class="full-width">
          <ng-container matColumnDef="label">
            <th mat-header-cell *matHeaderCellDef>Nom</th>
            <td mat-cell *matCellDef="let row">{{ row.label || '—' }}</td>
          </ng-container>

          <ng-container matColumnDef="date">
            <th mat-header-cell *matHeaderCellDef>Date</th>
            <td mat-cell *matCellDef="let row">{{ fmtDate(row.date) }}</td>
          </ng-container>

          <ng-container matColumnDef="venue">
            <th mat-header-cell *matHeaderCellDef>Lieu</th>
            <td mat-cell *matCellDef="let row">{{ row.venue?.name || '—' }}</td>
          </ng-container>

          <ng-container matColumnDef="city">
            <th mat-header-cell *matHeaderCellDef>Ville</th>
            <td mat-cell *matCellDef="let row">{{ row.venue?.city || '—' }}</td>
          </ng-container>

          <ng-container matColumnDef="createdBy">
            <th mat-header-cell *matHeaderCellDef>Créé par</th>
            <td mat-cell *matCellDef="let row">{{ row.createdBy?.email || '—' }}</td>
          </ng-container>

          <ng-container matColumnDef="actions">
            <th mat-header-cell *matHeaderCellDef></th>
            <td mat-cell *matCellDef="let row">
              <button mat-icon-button (click)="openEdit(row)">
                <mat-icon>edit</mat-icon>
              </button>
              <button mat-icon-button color="warn" (click)="confirmDelete(row)">
                <mat-icon>delete</mat-icon>
              </button>
            </td>
          </ng-container>

          <tr mat-header-row *matHeaderRowDef="columns"></tr>
          <tr mat-row *matRowDef="let row; columns: columns;"></tr>
        </table>
      </div>

      @if (deleteTarget()) {
        <div class="confirm-overlay" (click)="deleteTarget.set(null)">
          <div class="confirm-dialog" (click)="$event.stopPropagation()">
            <h3>Confirmer la suppression</h3>
            <p>Supprimer le concert <strong>{{ deleteTarget()!.label || deleteTarget()!.date }}</strong> ?</p>
            <div class="confirm-actions">
              <button mat-button (click)="deleteTarget.set(null)">Annuler</button>
              <button mat-raised-button color="warn" (click)="doDelete()" [disabled]="showStore.loading()">Supprimer</button>
            </div>
          </div>
        </div>
      }
    </app-admin-layout>
  `,
  styles: [`
    .page-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 1.5rem;
    }

    .page-title { font-size: 1.5rem; font-weight: 400; margin: 0; }

    .error-msg {
      color: #cf6679;
      border: 1px solid #cf6679;
      border-radius: 4px;
      padding: 0.75rem;
      margin-bottom: 1rem;
    }

    .table-wrapper { overflow-x: auto; }
    .full-width { width: 100%; }

    .confirm-overlay {
      position: fixed;
      inset: 0;
      background: rgba(0,0,0,0.5);
      display: flex;
      align-items: center;
      justify-content: center;
      z-index: 1000;
    }

    .confirm-dialog {
      background: #fff;
      border-radius: 8px;
      padding: 1.5rem;
      min-width: 320px;

      h3 { margin: 0 0 1rem; }
      p { color: rgba(0,0,0,0.6); margin: 0 0 1.5rem; }
    }

    .confirm-actions {
      display: flex;
      justify-content: flex-end;
      gap: 0.5rem;
    }
  `],
})
export class BackofficeShowsComponent implements OnInit {
  protected readonly showStore = inject(ShowStore);
  private readonly venueStore = inject(VenueStore);
  private readonly dialog = inject(MatDialog);

  protected readonly columns = ['label', 'date', 'venue', 'city', 'createdBy', 'actions'];
  protected readonly deleteTarget = signal<ShowWithCreator | null>(null);
  protected readonly fmtDate = formatDate;

  ngOnInit(): void {
    this.showStore.loadBackoffice();
    this.venueStore.load();
  }

  openCreate(): void {
    const ref = this.dialog.open(ShowFormDialogComponent, {
      maxWidth: '640px',
      width: '100%',
      data: { venues: this.venueStore.venues(), initial: null },
    });
    ref.afterClosed().subscribe(async (data: Omit<ShowData, 'id' | 'venue'> | undefined) => {
      if (!data) return;
      await this.showStore.create(data);
      if (!this.showStore.error()) this.showStore.loadBackoffice();
    });
  }

  openEdit(row: ShowWithCreator): void {
    const ref = this.dialog.open(ShowFormDialogComponent, {
      maxWidth: '640px',
      width: '100%',
      data: { venues: this.venueStore.venues(), initial: new Show(row) },
    });
    ref.afterClosed().subscribe(async (data: Omit<ShowData, 'id' | 'venue'> | undefined) => {
      if (!data) return;
      await this.showStore.update(row.id, data);
      if (!this.showStore.error()) this.showStore.loadBackoffice();
    });
  }

  confirmDelete(row: ShowWithCreator): void {
    this.deleteTarget.set(row);
  }

  async doDelete(): Promise<void> {
    const target = this.deleteTarget();
    if (!target) return;
    await this.showStore.remove(target.id);
    if (!this.showStore.error()) {
      this.deleteTarget.set(null);
      this.showStore.loadBackoffice();
    }
  }
}
