// front_vue/src/components/layout/PublicLayout.vue
<template>
  <div class="public-layout">
    <header class="public-header">
      <router-link to="/">
        <img src="@/assets/logo.png" alt="Portfolio" class="logo" />
      </router-link>
      <nav>
        <router-link to="/">Accueil</router-link>
        <router-link to="/shows">Concerts</router-link>
      </nav>
    </header>
    <main class="public-content">
      <slot />
    </main>
    <footer class="public-footer">
      <p>&copy; {{ new Date().getFullYear() }} Portfolio</p>
    </footer>
  </div>
</template>

<style scoped>
.public-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: #1a1a1a;
  color: #ffffff;
}

.public-header {
  height: 300px;
  background-image: url('@/assets/bg.jpg');
  background-size: cover;
  background-position: center;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1rem;
}

.logo {
  max-width: 400px;
  max-height: 200px;
  object-fit: contain;
}

nav {
  display: flex;
  gap: 2rem;
}

nav a {
  color: #ffffff;
  text-decoration: none;
  font-size: 1.1rem;
}

nav a.router-link-active {
  border-bottom: 2px solid #BB86FC;
}

.public-content {
  flex: 1;
  padding: 2rem;
  max-width: 1200px;
  margin: 0 auto;
  width: 100%;
}

.public-footer {
  padding: 1rem 2rem;
  text-align: center;
  color: #888;
  font-size: 0.9rem;
}
</style>

// front_angular/src/app/layout/public/public-layout.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-public-layout',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  template: `
    <div class="public-shell">
      <header class="public-header">
        <a routerLink="/">
          <img src="logo.png" alt="Portfolio" class="header-logo" />
        </a>
        <nav class="header-nav">
          <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Accueil</a>
          <a routerLink="/shows" routerLinkActive="active">Concerts</a>
        </nav>
      </header>

      <main class="public-main">
        <ng-content />
      </main>

      <footer class="public-footer">
        <p>&copy; {{ year }} Portfolio</p>
      </footer>
    </div>
  `,
  styles: [`
    .public-shell {
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      background-color: #1a1a1a;
      color: #fff;
    }

    .public-header {
      height: 300px;
      background-image: url('/bg.jpg');
      background-size: cover;
      background-position: center;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      gap: 1rem;
    }

    .header-logo {
      max-width: 400px;
      max-height: 200px;
      object-fit: contain;
    }

    .header-nav {
      display: flex;
      gap: 2rem;

      a {
        color: #ffffff;
        text-decoration: none;
        font-size: 1.1rem;
        padding-bottom: 2px;
        border-bottom: 2px solid transparent;

        &.active {
          border-bottom-color: #000;
        }
      }
    }

    .public-main {
      flex: 1;
      max-width: 1200px;
      width: 100%;
      margin: 0 auto;
      padding: 2rem 1rem;
      box-sizing: border-box;
    }

    .public-footer {
      padding: 1rem;
      text-align: center;
      color: #888;
      font-size: 0.9rem;

      p { margin: 0; }
    }
  `],
})
export class PublicLayoutComponent {
  readonly year = new Date().getFullYear();
}
