// front_react/src/pages/Register.tsx
import { useState } from 'react'
import {
  Alert, Box, Button, Card, CardContent, Checkbox,
  CircularProgress, FormControlLabel, IconButton, InputAdornment, TextField, Typography,
} from '@mui/material'
import { Visibility, VisibilityOff } from '@mui/icons-material'
import { Link } from 'react-router-dom'
import { authService } from '@/services/authService'

export default function Register() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirm, setConfirm] = useState('')
  const [isAdmin, setIsAdmin] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirm, setShowConfirm] = useState(false)
  const [loading, setLoading] = useState(false)
  const [serverError, setServerError] = useState('')
  const [success, setSuccess] = useState(false)
  const [errors, setErrors] = useState({ email: '', password: '', confirm: '' })

  function validate(): boolean {
    const e = { email: '', password: '', confirm: '' }
    if (!email) e.email = "L'email est requis"
    if (!password || password.length < 6) e.password = 'Minimum 6 caractères'
    if (password !== confirm) e.confirm = 'Les mots de passe ne correspondent pas'
    setErrors(e)
    return !e.email && !e.password && !e.confirm
  }

  async function submit(evt: React.FormEvent) {
    evt.preventDefault()
    if (!validate()) return
    setLoading(true)
    setServerError('')
    try {
      await authService.register(email, password, isAdmin)
      setSuccess(true)
    } catch (e: unknown) {
      setServerError(e instanceof Error ? e.message : 'Erreur lors de la création du compte.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#1a1a1a' }}>
      <Card sx={{ width: '100%', maxWidth: 420 }} elevation={8}>
        <CardContent sx={{ p: 3 }}>
          <Typography variant="h5" sx={{ fontWeight: 400, color: 'secondary.main', mb: 3 }}>
            Créer un compte
          </Typography>

          <Alert severity="warning" variant="outlined" sx={{ mb: 3, fontSize: '0.85rem' }}>
            Cette page est disponible <strong>uniquement pour la démonstration</strong>.<br />
            Elle n'existe pas en production.
          </Alert>

          {success ? (
            <>
              <Alert severity="success" sx={{ mb: 3 }}>
                Compte créé avec succès ! Vous pouvez maintenant vous connecter.
              </Alert>
              <Button variant="contained" fullWidth component={Link} to="/login">
                Se connecter
              </Button>
            </>
          ) : (
            <Box component="form" onSubmit={submit}>
              <TextField
                label="Email" type="email" fullWidth variant="outlined" size="small"
                value={email} onChange={(e) => setEmail(e.target.value)}
                error={!!errors.email} helperText={errors.email}
                autoComplete="email" sx={{ mb: 2 }}
              />
              <TextField
                label="Mot de passe" fullWidth variant="outlined" size="small"
                type={showPassword ? 'text' : 'password'}
                value={password} onChange={(e) => setPassword(e.target.value)}
                error={!!errors.password} helperText={errors.password}
                autoComplete="new-password"
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton onClick={() => setShowPassword(!showPassword)} edge="end" size="small">
                        {showPassword ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
                sx={{ mb: 2 }}
              />
              <TextField
                label="Confirmer le mot de passe" fullWidth variant="outlined" size="small"
                type={showConfirm ? 'text' : 'password'}
                value={confirm} onChange={(e) => setConfirm(e.target.value)}
                error={!!errors.confirm} helperText={errors.confirm}
                autoComplete="new-password"
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton onClick={() => setShowConfirm(!showConfirm)} edge="end" size="small">
                        {showConfirm ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
                sx={{ mb: 2 }}
              />
              <FormControlLabel
                control={<Checkbox checked={isAdmin} onChange={(e) => setIsAdmin(e.target.checked)} color="warning" />}
                label={
                  <Typography sx={{ fontSize: '0.9rem' }}>
                    Créer en tant qu'<strong>ADMIN</strong>{' '}
                    <Typography component="span" sx={{ fontSize: '0.75rem', color: 'text.secondary' }}>(démo uniquement)</Typography>
                  </Typography>
                }
                sx={{ mb: 2 }}
              />
              {serverError && <Alert severity="error" sx={{ mb: 2 }}>{serverError}</Alert>}
              <Button type="submit" variant="contained" fullWidth size="large" disabled={loading}>
                {loading ? <CircularProgress size={22} color="inherit" /> : 'Créer le compte'}
              </Button>
            </Box>
          )}

          <Box sx={{ textAlign: 'center', mt: 2 }}>
            <Typography component={Link} to="/login" sx={{ fontSize: '0.75rem', color: '#888', textDecoration: 'none', '&:hover': { color: '#aaa' } }}>
              Déjà un compte ? Se connecter
            </Typography>
          </Box>
        </CardContent>
      </Card>
    </Box>
  )
}

// front_angular/src/app/pages/register/register.component.ts
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../core/services/auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    FormsModule,
    RouterLink,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
  ],
  template: `
    <div class="register-wrapper">
      <mat-card class="register-card">
        <mat-card-content>
          <h2 class="card-title">Créer un compte</h2>

          <div class="demo-warning">
            Cette page est disponible <strong>uniquement pour la démonstration</strong>.<br />
            Elle n'existe pas en production.
          </div>

          @if (success()) {
            <div class="success-msg">Compte créé avec succès ! Vous pouvez maintenant vous connecter.</div>
            <a mat-raised-button color="primary" routerLink="/login" class="full-width">Se connecter</a>
          } @else {
            <form (ngSubmit)="submit()">
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>Email</mat-label>
                <input matInput type="email" name="email" [(ngModel)]="email"
                       required autocomplete="email" />
                @if (emailError()) { <mat-error>{{ emailError() }}</mat-error> }
              </mat-form-field>

              <mat-form-field appearance="outline" class="full-width">
                <mat-label>Mot de passe</mat-label>
                <input matInput [type]="showPassword() ? 'text' : 'password'"
                       name="password" [(ngModel)]="password"
                       required autocomplete="new-password" />
                <button mat-icon-button matSuffix type="button"
                        (click)="showPassword.set(!showPassword())">
                  <mat-icon>{{ showPassword() ? 'visibility_off' : 'visibility' }}</mat-icon>
                </button>
                @if (passwordError()) { <mat-error>{{ passwordError() }}</mat-error> }
              </mat-form-field>

              <mat-form-field appearance="outline" class="full-width">
                <mat-label>Confirmer le mot de passe</mat-label>
                <input matInput [type]="showConfirm() ? 'text' : 'password'"
                       name="confirm" [(ngModel)]="confirm"
                       required autocomplete="new-password" />
                <button mat-icon-button matSuffix type="button"
                        (click)="showConfirm.set(!showConfirm())">
                  <mat-icon>{{ showConfirm() ? 'visibility_off' : 'visibility' }}</mat-icon>
                </button>
                @if (confirmError()) { <mat-error>{{ confirmError() }}</mat-error> }
              </mat-form-field>

              <mat-checkbox [(ngModel)]="isAdmin" name="isAdmin" color="warn" class="admin-check">
                Créer en tant qu'<strong>ADMIN</strong>
                <span class="admin-hint">(démo uniquement)</span>
              </mat-checkbox>

              @if (serverError()) {
                <div class="error-msg">{{ serverError() }}</div>
              }

              <button mat-raised-button color="primary" type="submit"
                      class="full-width submit-btn" [disabled]="loading()">
                @if (loading()) { <mat-spinner diameter="22" /> } @else { Créer le compte }
              </button>
            </form>
          }

          <div class="login-link">
            <a routerLink="/login">Déjà un compte ? Se connecter</a>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .register-wrapper {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #1a1a1a;
    }

    .register-card {
      width: 100%;
      max-width: 420px;
    }

    .card-title {
      font-weight: 400;
      color: #bb86fc;
      margin: 0 0 1.5rem;
      font-size: 1.4rem;
    }

    .demo-warning {
      border: 1px solid #ffb74d;
      color: #ffb74d;
      border-radius: 4px;
      padding: 0.75rem;
      font-size: 0.85rem;
      margin-bottom: 1.5rem;
      line-height: 1.5;
    }

    .full-width { width: 100%; }

    .admin-check {
      display: block;
      margin-bottom: 1rem;
      font-size: 0.9rem;
    }

    .admin-hint {
      font-size: 0.75rem;
      color: #888;
      margin-left: 0.25rem;
    }

    .submit-btn {
      margin-top: 0.5rem;
      height: 48px;
    }

    .error-msg {
      color: #cf6679;
      border: 1px solid #cf6679;
      border-radius: 4px;
      padding: 0.5rem 0.75rem;
      font-size: 0.9rem;
      margin-bottom: 1rem;
    }

    .success-msg {
      background: rgba(129, 199, 132, 0.15);
      border: 1px solid #81c784;
      color: #81c784;
      border-radius: 4px;
      padding: 0.75rem;
      margin-bottom: 1.5rem;
    }

    .login-link {
      text-align: center;
      margin-top: 1rem;

      a {
        font-size: 0.75rem;
        color: #888;
        text-decoration: none;
        &:hover { color: #aaa; }
      }
    }
  `],
})
export class RegisterComponent {
  private readonly authService = inject(AuthService);

  readonly loading = signal(false);
  readonly serverError = signal('');
  readonly success = signal(false);
  readonly showPassword = signal(false);
  readonly showConfirm = signal(false);
  readonly emailError = signal('');
  readonly passwordError = signal('');
  readonly confirmError = signal('');

  email = '';
  password = '';
  confirm = '';
  isAdmin = false;

  submit(): void {
    this.emailError.set(this.email ? '' : "L'email est requis");
    this.passwordError.set(
      !this.password ? 'Le mot de passe est requis' :
      this.password.length < 6 ? 'Minimum 6 caractères' : ''
    );
    this.confirmError.set(
      this.password !== this.confirm ? 'Les mots de passe ne correspondent pas' : ''
    );
    if (this.emailError() || this.passwordError() || this.confirmError()) return;

    this.loading.set(true);
    this.serverError.set('');
    this.authService.register(this.email, this.password, this.isAdmin).subscribe({
      next: () => this.success.set(true),
      error: (e: Error) => {
        this.serverError.set(e.message || 'Erreur lors de la création du compte.');
        this.loading.set(false);
      },
      complete: () => this.loading.set(false),
    });
  }
}
