// front_vue/src/components/backoffice/ShowForm.vue
<template>
  <v-form @submit.prevent="submit" ref="formRef">
    <p class="text-h6 mb-4" data-testid="show-dialog-title">{{ initial ? 'Modifier le concert' : 'Nouveau concert' }}</p>
    <v-row>
      <v-col cols="12" sm="7">
        <v-text-field
          v-model="form.label"
          label="Nom du concert"
          variant="outlined"
          density="comfortable"
          data-testid="show-label-input"
        />
      </v-col>
      <v-col cols="12" sm="5">
        <v-text-field
          v-model="form.date"
          label="Date *"
          type="datetime-local"
          variant="outlined"
          density="comfortable"
          :rules="[required]"
          data-testid="show-date-input"
        />
      </v-col>
      <v-col cols="12">
        <v-select
          v-model="form.venueId"
          :items="venues"
          item-title="name"
          item-value="id"
          label="Lieu *"
          placeholder="Choisir un lieu"
          variant="outlined"
          density="comfortable"
          :rules="[requiredVenue]"
          no-data-text="Aucun lieu disponible — créez-en un d'abord."
        />
      </v-col>
      <v-col cols="12">
        <v-textarea
          v-model="form.details"
          label="Détails"
          variant="outlined"
          density="comfortable"
          rows="3"
          auto-grow
        />
      </v-col>
    </v-row>
    <div class="d-flex gap-2 mt-2">
      <v-btn type="submit" color="primary" :loading="loading">Enregistrer</v-btn>
      <v-btn variant="text" @click="$emit('cancel')">Annuler</v-btn>
    </div>
  </v-form>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import type { Venue, Show, ShowData } from '@portfolio/shared'

const props = defineProps<{ venues: Venue[]; loading?: boolean; initial?: Show }>()

const emit = defineEmits<{
  submit: [data: Omit<ShowData, 'id' | 'venue'>]
  cancel: []
}>()

const formRef = ref()
const form = reactive({
  label: '',
  date: '',
  venueId: null as number | null,
  details: '',
})

onMounted(() => {
  if (props.initial) {
    const d = props.initial.date
    const pad = (n: number) => String(n).padStart(2, '0')
    const localStr = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`
    Object.assign(form, {
      label: props.initial.label ?? '',
      date: localStr,
      venueId: props.initial.venueId,
      details: props.initial.details ?? '',
    })
  }
})

const required = (v: string) => !!v || 'Champ requis'
const requiredVenue = (v: number | null) => v !== null || 'Champ requis'

async function submit() {
  const { valid } = await formRef.value.validate()
  if (!valid) return
  emit('submit', {
    label: form.label || undefined,
    details: form.details || undefined,
    date: new Date(form.date).toISOString(),
    venueId: form.venueId!,
  })
  if (!props.initial) {
    Object.assign(form, { label: '', date: '', venueId: null, details: '' })
  }
}
</script>

// front_react/src/components/backoffice/ShowForm.tsx
import { useEffect, useState } from 'react'
import { Box, Button, Grid, MenuItem, TextField, Typography } from '@mui/material'
import type { ShowData, Venue } from '@portfolio/shared'

interface Props {
  venues: Venue[]
  initial?: ShowData
  loading?: boolean
  onSubmit: (data: Omit<ShowData, 'id' | 'venue'>) => void
  onCancel: () => void
}

function toLocalDatetimeString(date: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`
}

export default function ShowForm({ venues, initial, loading, onSubmit, onCancel }: Props) {
  const [label, setLabel] = useState('')
  const [date, setDate] = useState('')
  const [venueId, setVenueId] = useState<number | ''>('')
  const [details, setDetails] = useState('')
  const [errors, setErrors] = useState({ date: '', venueId: '' })

  useEffect(() => {
    if (initial) {
      setLabel(initial.label ?? '')
      setDate(toLocalDatetimeString(new Date(initial.date)))
      setVenueId(initial.venueId)
      setDetails(initial.details ?? '')
    }
  }, [initial])

  function validate(): boolean {
    const e = { date: '', venueId: '' }
    if (!date) e.date = 'Champ requis'
    if (!venueId) e.venueId = 'Champ requis'
    setErrors(e)
    return !e.date && !e.venueId
  }

  function submit(evt: React.FormEvent) {
    evt.preventDefault()
    if (!validate()) return
    onSubmit({
      label: label || undefined,
      details: details || undefined,
      date: new Date(date).toISOString(),
      venueId: venueId as number,
    })
    if (!initial) {
      setLabel(''); setDate(''); setVenueId(''); setDetails('')
    }
  }

  return (
    <Box component="form" onSubmit={submit}>
      <Typography variant="h6" sx={{ mb: 3 }} data-testid="show-dialog-title">{initial ? 'Modifier le concert' : 'Nouveau concert'}</Typography>
      <Grid container spacing={2}>
        <Grid item xs={12} sm={7}>
          <TextField label="Nom du concert" fullWidth variant="outlined" size="small"
            value={label} onChange={(e) => setLabel(e.target.value)}
            inputProps={{ 'data-testid': 'show-label-input' }} />
        </Grid>
        <Grid item xs={12} sm={5}>
          <TextField label="Date *" type="datetime-local" fullWidth variant="outlined" size="small"
            value={date} onChange={(e) => setDate(e.target.value)}
            error={!!errors.date} helperText={errors.date}
            InputLabelProps={{ shrink: true }}
            inputProps={{ 'data-testid': 'show-date-input' }} />
        </Grid>
        <Grid item xs={12}>
          <TextField
            select label="Lieu *" fullWidth variant="outlined" size="small"
            value={venueId} onChange={(e) => setVenueId(Number(e.target.value))}
            error={!!errors.venueId} helperText={errors.venueId || (venues.length === 0 ? 'Aucun lieu disponible — créez-en un d\'abord.' : '')}
            data-testid="show-venue-select"
          >
            {venues.map((v) => (
              <MenuItem key={v.id} value={v.id}>{v.name}</MenuItem>
            ))}
          </TextField>
        </Grid>
        <Grid item xs={12}>
          <TextField label="Détails" fullWidth variant="outlined" size="small" multiline rows={3}
            value={details} onChange={(e) => setDetails(e.target.value)} />
        </Grid>
      </Grid>
      <Box sx={{ display: 'flex', gap: 1, mt: 3 }}>
        <Button type="submit" variant="contained" disabled={loading} data-testid="save-btn">Enregistrer</Button>
        <Button variant="text" onClick={onCancel}>Annuler</Button>
      </Box>
    </Box>
  )
}
