// front_react/src/pages/Login.tsx
import { useEffect, useRef, useState } from 'react'
import {
  Alert, Box, Button, Card, CardContent, CircularProgress,
  IconButton, InputAdornment, TextField, Typography,
} from '@mui/material'
import { Visibility, VisibilityOff } from '@mui/icons-material'
import { Link, useNavigate } from 'react-router-dom'
import { authService } from '@/services/authService'
import { useAuthStore } from '@/stores/authStore'

type Step = 'credentials' | 'mfa' | 'mfa-setup'

export default function Login() {
  const navigate = useNavigate()
  const setToken = useAuthStore((s) => s.setToken)

  const [step, setStep] = useState<Step>('credentials')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [mfaCode, setMfaCode] = useState('')
  const [mfaSetupCode, setMfaSetupCode] = useState('')
  const [qrCodeDataURL, setQrCodeDataURL] = useState('')
  const [pendingSetupToken, setPendingSetupToken] = useState('')
  const [pendingUserId, setPendingUserId] = useState<number | null>(null)
  const [loading, setLoading] = useState(false)
  const [serverError, setServerError] = useState('')
  const [errors, setErrors] = useState({ email: '', password: '' })

  const mfaInputRef = useRef<HTMLInputElement>(null)
  const mfaSetupInputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    if (step === 'mfa') mfaInputRef.current?.focus()
    if (step === 'mfa-setup') mfaSetupInputRef.current?.focus()
  }, [step])

  function validate(): boolean {
    const e = { email: '', password: '' }
    if (!email) e.email = "L'email est requis"
    if (!password) e.password = 'Le mot de passe est requis'
    setErrors(e)
    return !e.email && !e.password
  }

  async function submitCredentials(evt: React.FormEvent) {
    evt.preventDefault()
    if (!validate()) return
    setLoading(true)
    setServerError('')
    try {
      const res = await authService.login(email, password)
      if (res.mfaSetupRequired && res.setupToken) {
        setPendingSetupToken(res.setupToken)
        setStep('mfa-setup')
        const setup = await authService.setupMfaWithToken(res.setupToken)
        setQrCodeDataURL(setup.qrCodeDataURL)
      } else if (res.mfaRequired && res.userId) {
        setPendingUserId(res.userId)
        setStep('mfa')
      } else if (res.token) {
        setToken(res.token)
        navigate('/backoffice/venues')
      }
    } catch {
      setServerError('Identifiants invalides.')
    } finally {
      setLoading(false)
    }
  }

  async function submitMfaSetup(evt: React.FormEvent) {
    evt.preventDefault()
    if (!pendingSetupToken || mfaSetupCode.length < 6) return
    setLoading(true)
    setServerError('')
    try {
      const res = await authService.confirmMfaWithToken(mfaSetupCode, pendingSetupToken)
      setToken(res.token)
      navigate('/backoffice/venues')
    } catch {
      setServerError('Code invalide. Réessayez.')
      setMfaSetupCode('')
    } finally {
      setLoading(false)
    }
  }

  async function submitMfa(evt: React.FormEvent) {
    evt.preventDefault()
    if (!pendingUserId || mfaCode.length < 6) return
    setLoading(true)
    setServerError('')
    try {
      const res = await authService.verifyMfa(pendingUserId, mfaCode)
      setToken(res.token)
      navigate('/backoffice/venues')
    } catch {
      setServerError('Code invalide. Réessayez.')
      setMfaCode('')
    } finally {
      setLoading(false)
    }
  }

  const stepTitle = step === 'credentials' ? 'Connexion' : step === 'mfa' ? 'Vérification MFA' : 'Configuration MFA'

  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#1a1a1a' }}>
      <Card sx={{ width: '100%', maxWidth: 420 }} elevation={8}>
        <CardContent sx={{ p: 3 }}>
          <Typography variant="h5" sx={{ fontWeight: 400, color: 'secondary.main', mb: 3 }}>
            {stepTitle}
          </Typography>

          {step === 'credentials' && (
            <Box component="form" onSubmit={submitCredentials}>
              <TextField
                label="Email" type="email" fullWidth variant="outlined" size="small"
                value={email} onChange={(e) => setEmail(e.target.value)}
                error={!!errors.email} helperText={errors.email}
                autoComplete="email" sx={{ mb: 2 }}
              />
              <TextField
                label="Mot de passe" fullWidth variant="outlined" size="small"
                type={showPassword ? 'text' : 'password'}
                value={password} onChange={(e) => setPassword(e.target.value)}
                error={!!errors.password} helperText={errors.password}
                autoComplete="current-password"
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton onClick={() => setShowPassword(!showPassword)} edge="end" size="small">
                        {showPassword ? <VisibilityOff /> : <Visibility />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
                sx={{ mb: 3 }}
              />
              {serverError && <Alert severity="error" sx={{ mb: 2 }}>{serverError}</Alert>}
              <Button type="submit" variant="contained" fullWidth size="large" disabled={loading}>
                {loading ? <CircularProgress size={22} color="inherit" /> : 'Se connecter'}
              </Button>
            </Box>
          )}

          {step === 'mfa-setup' && (
            <Box component="form" onSubmit={submitMfaSetup}>
              {!qrCodeDataURL ? (
                <>
                  <Typography sx={{ color: '#aaa', fontSize: '0.9rem', mb: 2 }}>
                    Votre administrateur a activé le MFA sur votre compte. Chargement du QR code…
                  </Typography>
                  <CircularProgress sx={{ display: 'block', mx: 'auto' }} />
                </>
              ) : (
                <>
                  <Typography sx={{ color: '#aaa', fontSize: '0.9rem', mb: 2 }}>
                    Scannez ce QR code avec Google Authenticator ou une application TOTP compatible, puis entrez le code généré.
                  </Typography>
                  <Box sx={{ display: 'flex', justifyContent: 'center', mb: 3 }}>
                    <img src={qrCodeDataURL} alt="QR Code MFA" width={180} height={180} />
                  </Box>
                  <OtpInput value={mfaSetupCode} onChange={setMfaSetupCode} inputRef={mfaSetupInputRef} />
                  {serverError && <Alert severity="error" sx={{ mb: 2 }}>{serverError}</Alert>}
                  <Button type="submit" variant="contained" fullWidth size="large" disabled={loading || mfaSetupCode.length < 6}>
                    {loading ? <CircularProgress size={22} color="inherit" /> : 'Confirmer'}
                  </Button>
                </>
              )}
            </Box>
          )}

          {step === 'mfa' && (
            <Box component="form" onSubmit={submitMfa}>
              <Typography sx={{ color: '#aaa', fontSize: '0.9rem', mb: 2 }}>
                Saisissez le code à 6 chiffres affiché dans votre application Google Authenticator.
              </Typography>
              <OtpInput value={mfaCode} onChange={setMfaCode} inputRef={mfaInputRef} />
              {serverError && <Alert severity="error" sx={{ mb: 2 }}>{serverError}</Alert>}
              <Button type="submit" variant="contained" fullWidth size="large" disabled={loading || mfaCode.length < 6}>
                {loading ? <CircularProgress size={22} color="inherit" /> : 'Vérifier'}
              </Button>
              <Button variant="text" fullWidth sx={{ mt: 1 }} onClick={() => setStep('credentials')}>
                Retour
              </Button>
            </Box>
          )}

          <Box sx={{ textAlign: 'center', mt: 2 }}>
            <Typography component={Link} to="/register" sx={{ fontSize: '0.75rem', color: '#888', textDecoration: 'none', '&:hover': { color: '#aaa' } }}>
              Créer un compte (démo)
            </Typography>
          </Box>
        </CardContent>
      </Card>
    </Box>
  )
}

function OtpInput({ value, onChange, inputRef }: {
  value: string
  onChange: (v: string) => void
  inputRef?: React.RefObject<HTMLInputElement>
}) {
  return (
    <TextField
      inputRef={inputRef}
      label="Code à 6 chiffres"
      fullWidth variant="outlined" size="small"
      value={value}
      onChange={(e) => {
        const v = e.target.value.replace(/\D/g, '').slice(0, 6)
        onChange(v)
      }}
      inputProps={{ inputMode: 'numeric', pattern: '[0-9]*', maxLength: 6 }}
      sx={{ mb: 3, letterSpacing: '0.5em', '& input': { textAlign: 'center', fontSize: '1.5rem' } }}
    />
  )
}

// front_angular/src/app/pages/login/login.component.ts
import { Component, inject, signal, ViewChild, ElementRef, AfterViewInit, effect } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AuthService } from '../../core/services/auth.service';
import { AuthStore } from '../../core/stores/auth.store';

type Step = 'credentials' | 'mfa' | 'mfa-setup';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    FormsModule,
    RouterLink,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
  ],
  template: `
    <div class="login-wrapper">
      <mat-card class="login-card">
        <mat-card-content>
          <h2 class="card-title">{{ stepTitle() }}</h2>

          @if (step() === 'credentials') {
            <form (ngSubmit)="submitCredentials()">
              <mat-form-field appearance="outline" class="full-width">
                <mat-label>Email</mat-label>
                <input matInput type="email" name="email" [(ngModel)]="email"
                       required autocomplete="email" />
                @if (emailError()) { <mat-error>{{ emailError() }}</mat-error> }
              </mat-form-field>

              <mat-form-field appearance="outline" class="full-width">
                <mat-label>Mot de passe</mat-label>
                <input matInput [type]="showPassword() ? 'text' : 'password'"
                       name="password" [(ngModel)]="password"
                       required autocomplete="current-password" />
                <button mat-icon-button matSuffix type="button"
                        (click)="showPassword.set(!showPassword())">
                  <mat-icon>{{ showPassword() ? 'visibility_off' : 'visibility' }}</mat-icon>
                </button>
                @if (passwordError()) { <mat-error>{{ passwordError() }}</mat-error> }
              </mat-form-field>

              @if (serverError()) {
                <div class="error-msg">{{ serverError() }}</div>
              }

              <button mat-raised-button color="primary" type="submit"
                      class="full-width submit-btn" [disabled]="loading()">
                @if (loading()) { <mat-spinner diameter="22" /> } @else { Se connecter }
              </button>
            </form>
          }

          @if (step() === 'mfa-setup') {
            <form (ngSubmit)="submitMfaSetup()">
              @if (!qrCodeDataURL()) {
                <p class="hint">Votre administrateur a activé le MFA. Chargement du QR code…</p>
                <mat-spinner style="margin: auto" />
              } @else {
                <p class="hint">Scannez ce QR code avec Google Authenticator ou une app TOTP, puis entrez le code généré.</p>
                <div class="qr-wrapper">
                  <img [src]="qrCodeDataURL()" alt="QR Code MFA" width="180" height="180" />
                </div>
                <mat-form-field appearance="outline" class="full-width otp-field">
                  <mat-label>Code à 6 chiffres</mat-label>
                  <input matInput name="mfaSetupCode" [(ngModel)]="mfaSetupCode"
                         inputmode="numeric" maxlength="6"
                         (input)="filterDigits('setup')" #setupInput />
                </mat-form-field>
                @if (serverError()) { <div class="error-msg">{{ serverError() }}</div> }
                <button mat-raised-button color="primary" type="submit"
                        class="full-width submit-btn"
                        [disabled]="loading() || mfaSetupCode.length < 6">
                  @if (loading()) { <mat-spinner diameter="22" /> } @else { Confirmer }
                </button>
              }
            </form>
          }

          @if (step() === 'mfa') {
            <form (ngSubmit)="submitMfa()">
              <p class="hint">Saisissez le code à 6 chiffres de votre application Google Authenticator.</p>
              <mat-form-field appearance="outline" class="full-width otp-field">
                <mat-label>Code à 6 chiffres</mat-label>
                <input matInput name="mfaCode" [(ngModel)]="mfaCode"
                       inputmode="numeric" maxlength="6"
                       (input)="filterDigits('mfa')" #mfaInput />
              </mat-form-field>
              @if (serverError()) { <div class="error-msg">{{ serverError() }}</div> }
              <button mat-raised-button color="primary" type="submit"
                      class="full-width submit-btn"
                      [disabled]="loading() || mfaCode.length < 6">
                @if (loading()) { <mat-spinner diameter="22" /> } @else { Vérifier }
              </button>
              <button mat-button type="button" class="full-width"
                      (click)="step.set('credentials')">Retour</button>
            </form>
          }

          <div class="register-link">
            <a routerLink="/register">Créer un compte (démo)</a>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  `,
  styles: [`
    .login-wrapper {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background-color: #1a1a1a;
    }

    .login-card {
      width: 100%;
      max-width: 420px;
    }

    .card-title {
      font-weight: 400;
      color: #bb86fc;
      margin: 0 0 1.5rem;
      font-size: 1.4rem;
    }

    .full-width { width: 100%; }

    .submit-btn {
      margin-top: 0.5rem;
      height: 48px;
    }

    .hint {
      color: #aaa;
      font-size: 0.9rem;
      margin: 0 0 1rem;
    }

    .qr-wrapper {
      display: flex;
      justify-content: center;
      margin-bottom: 1.5rem;
    }

    .otp-field ::ng-deep input {
      text-align: center;
      font-size: 1.5rem;
      letter-spacing: 0.5em;
    }

    .error-msg {
      color: #cf6679;
      border: 1px solid #cf6679;
      border-radius: 4px;
      padding: 0.5rem 0.75rem;
      font-size: 0.9rem;
      margin-bottom: 1rem;
    }

    .register-link {
      text-align: center;
      margin-top: 1rem;

      a {
        font-size: 0.75rem;
        color: #888;
        text-decoration: none;
        &:hover { color: #aaa; }
      }
    }
  `],
})
export class LoginComponent implements AfterViewInit {
  @ViewChild('mfaInput') mfaInputRef?: ElementRef<HTMLInputElement>;
  @ViewChild('setupInput') setupInputRef?: ElementRef<HTMLInputElement>;

  private readonly authService = inject(AuthService);
  private readonly authStore = inject(AuthStore);
  private readonly router = inject(Router);

  readonly step = signal<Step>('credentials');
  readonly loading = signal(false);
  readonly serverError = signal('');
  readonly showPassword = signal(false);
  readonly qrCodeDataURL = signal('');
  readonly emailError = signal('');
  readonly passwordError = signal('');

  email = '';
  password = '';
  mfaCode = '';
  mfaSetupCode = '';

  private pendingSetupToken = '';
  private pendingUserId: number | null = null;

  readonly stepTitle = () => {
    const s = this.step();
    if (s === 'mfa') return 'Vérification MFA';
    if (s === 'mfa-setup') return 'Configuration MFA';
    return 'Connexion';
  };

  constructor() {
    effect(() => {
      const s = this.step();
      setTimeout(() => {
        if (s === 'mfa') this.mfaInputRef?.nativeElement.focus();
        if (s === 'mfa-setup') this.setupInputRef?.nativeElement.focus();
      }, 50);
    });
  }

  ngAfterViewInit(): void {}

  filterDigits(target: 'mfa' | 'setup'): void {
    if (target === 'mfa') {
      this.mfaCode = this.mfaCode.replace(/\D/g, '').slice(0, 6);
    } else {
      this.mfaSetupCode = this.mfaSetupCode.replace(/\D/g, '').slice(0, 6);
    }
  }

  submitCredentials(): void {
    this.emailError.set(this.email ? '' : "L'email est requis");
    this.passwordError.set(this.password ? '' : 'Le mot de passe est requis');
    if (this.emailError() || this.passwordError()) return;

    this.loading.set(true);
    this.serverError.set('');
    this.authService.login(this.email, this.password).subscribe({
      next: (res) => {
        if (res.mfaSetupRequired && res.setupToken) {
          this.pendingSetupToken = res.setupToken;
          this.step.set('mfa-setup');
          this.authService.setupMfaWithToken(res.setupToken).subscribe({
            next: (setup) => this.qrCodeDataURL.set(setup.qrCodeDataURL),
          });
        } else if (res.mfaRequired && res.userId) {
          this.pendingUserId = res.userId;
          this.step.set('mfa');
        } else if (res.token) {
          this.authStore.setToken(res.token);
          this.router.navigate(['/backoffice/venues']);
        }
      },
      error: () => {
        this.serverError.set('Identifiants invalides.');
        this.loading.set(false);
      },
      complete: () => this.loading.set(false),
    });
  }

  submitMfaSetup(): void {
    if (!this.pendingSetupToken || this.mfaSetupCode.length < 6) return;
    this.loading.set(true);
    this.serverError.set('');
    this.authService.confirmMfaWithToken(this.mfaSetupCode, this.pendingSetupToken).subscribe({
      next: (res) => {
        this.authStore.setToken(res.token);
        this.router.navigate(['/backoffice/venues']);
      },
      error: () => {
        this.serverError.set('Code invalide. Réessayez.');
        this.mfaSetupCode = '';
        this.loading.set(false);
      },
      complete: () => this.loading.set(false),
    });
  }

  submitMfa(): void {
    if (!this.pendingUserId || this.mfaCode.length < 6) return;
    this.loading.set(true);
    this.serverError.set('');
    this.authService.verifyMfa(this.pendingUserId, this.mfaCode).subscribe({
      next: (res) => {
        this.authStore.setToken(res.token);
        this.router.navigate(['/backoffice/venues']);
      },
      error: () => {
        this.serverError.set('Code invalide. Réessayez.');
        this.mfaCode = '';
        this.loading.set(false);
      },
      complete: () => this.loading.set(false),
    });
  }
}
